#!/usr/bin/env node
'use strict';

import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { readStdinJson, getCwd, readUnifiedState, writeUnifiedState } from './lib/state.mjs';
import { isPersistentModeActiveFromState, getPersistentModeMessageFromState } from './lib/persistent-mode.mjs';

const data = readStdinJson();
if (!data) {
  console.log(JSON.stringify({ continue: true }));
  process.exit(0);
}

const cwd = getCwd(data);
const hints = [];

// Extract notification info
// Claude Code Notification hook receives: message about agent/subagent completion
const message = data.message || data.notification || '';
const messageStr = typeof message === 'string' ? message : JSON.stringify(message);

// Agent completion chaining — all 16 agents
const chains = [
  { match: 'Etask-executor',     hint: '[CHAIN] Etask-executor completed. Run Earchive-executor in background to archive completed tasks.' },
  { match: 'Erefresh-executor',  hint: 'Analysis updated by Erefresh-executor. Proceed with user\'s request using fresh .qe/analysis/ data.' },
  { match: 'Ecompact-executor',  hint: 'Context saved by Ecompact-executor. Safe to continue. Use /Qresume in next session to restore.' },
  { match: 'Earchive-executor',  hint: 'Tasks archived by Earchive-executor. Completed files moved to .qe/.archive/.' },
  { match: 'Ecommit-executor',   hint: 'Commit created by Ecommit-executor. Report commit hash and summary to user.' },
  { match: 'Ecode-debugger',     hint: 'Ecode-debugger completed analysis. Review findings and apply suggested fixes.' },
  { match: 'Ecode-doc-writer',   hint: 'Documentation generated by Ecode-doc-writer. Review output with user.' },
  { match: 'Ecode-reviewer',     hint: 'Code review completed by Ecode-reviewer. Present findings and ask user about fixes.' },
  { match: 'Ecode-test-engineer', hint: 'Tests written by Ecode-test-engineer. Run tests to verify they pass.' },
  { match: 'Edeep-researcher',   hint: 'Research completed by Edeep-researcher. Summarize findings for user.' },
  { match: 'Edoc-generator',     hint: 'Document generated by Edoc-generator. Check output file and report path to user.' },
  { match: 'Egrad-writer',       hint: 'Chapter draft completed by Egrad-writer. Review academic style and citations.' },
  { match: 'Ehandoff-executor',  hint: 'Handoff document generated by Ehandoff-executor. Saved to .qe/handoffs/.' },
  { match: 'Epm-planner',        hint: 'Planning document created by Epm-planner. Review and confirm with user.' },
  { match: 'Eprofile-collector',  hint: 'Profile updated by Eprofile-collector. Data saved to .qe/profile/.' },
  { match: 'Eqa-orchestrator',   hint: '[CHAIN] Eqa-orchestrator completed quality loop. Report test/review/fix results to user.' },
  { match: 'codex-rescue',       hint: '[CODEX] Codex rescue returned Done. WARNING: Done does NOT mean files are written — Codex companion runs async and can take 15-60 min. You MUST now execute this polling loop: (1) Run `git diff --stat` immediately. (2) If changes found, proceed to verify. (3) If NO changes, start background polling: run `sleep 30 && git diff --stat` in a loop up to 120 times (1 hour). Log every 10th poll to user: "Codex polling... Xm elapsed". (4) If changes appear at any point, stop polling and proceed to verify. (5) After 1 HOUR with no changes, use AskUserQuestion: "Codex companion has not written files after 1 hour. (a) Keep waiting 1 more hour (b) Retry with Codex (c) Fallback to Claude (d) Check process: ps aux | grep codex". If user picks (a), repeat the 1-hour loop. Keep repeating as long as user says keep waiting. Do NOT ask before 1 hour. Do NOT say "waiting" without actually running sleep+diff.' },
  { match: 'codex-review',       hint: '[CODEX] Codex review completed. Parse review findings and map to supervision verdict.' },
];

let agentChainMatched = false;
for (const { match, hint } of chains) {
  // Use word boundary match to prevent partial agent name collisions
  const regex = new RegExp(`\\b${match}\\b`);
  if (regex.test(messageStr)) {
    hints.push(hint);
    agentChainMatched = true;
    break;  // One chain action per notification
  }
}

// --- Persistent Mode Reinforcement ---
// When persistent mode is active and the notification contains completion-like
// patterns (e.g., agent finished, task done), inject a reinforcement message
// to prevent Claude from wrapping up prematurely.
//
// IMPORTANT: Skip reinforcement if an agent chain was matched above.
// Agent completion is expected "done" — reinforcing "don't stop" here
// would prevent the caller from processing the agent's results.
try {
  if (!agentChainMatched) {
    const unifiedState = readUnifiedState(cwd);
    const pm = isPersistentModeActiveFromState(unifiedState);
    if (pm.active) {
      const completionPatterns = /\b(complet|finish|done|wrap|final|conclud|summar|handoff|hand off|result|output ready)\b/i;
      if (completionPatterns.test(messageStr)) {
        const reinforcement = getPersistentModeMessageFromState(unifiedState);
        if (reinforcement) {
          // Increment reinforcement counter in state
          if (unifiedState.persistentMode) {
            unifiedState.persistentMode.reinforcements = (unifiedState.persistentMode.reinforcements || 0) + 1;
            try { writeUnifiedState(cwd, unifiedState); } catch {}
          }
          hints.push(reinforcement);
        }
      }
    }
  }
} catch {
  // Fault tolerance — never let persistent mode crash the notification hook
}

if (hints.length > 0) {
  console.log(JSON.stringify({
    continue: true,
    hookSpecificOutput: {
      hookEventName: "Notification",
      additionalContext: `[QE] ${hints.join(' | ')}`
    }
  }));
} else {
  console.log(JSON.stringify({ continue: true }));
}
