#!/usr/bin/env node
'use strict';

import { readFileSync, existsSync, unlinkSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { spawn } from 'child_process';
import { readStdinJson, getCwd, readUnifiedState, writeUnifiedState } from './lib/state.mjs';
import { isPersistentModeActiveFromState, getPersistentModeMessageFromState } from './lib/persistent-mode.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));

const data = readStdinJson();
if (!data) {
  console.log(JSON.stringify({ continue: true }));
  process.exit(0);
}

const cwd = getCwd(data);
const hints = [];

// Extract notification info
// Claude Code Notification hook receives: message about agent/subagent completion
const message = data.message || data.notification || '';
const messageStr = typeof message === 'string' ? message : JSON.stringify(message);

// Agent completion chaining — all 16 agents + codex
const chains = [
  { match: 'Etask-executor',     hint: '[CHAIN] Etask-executor completed. Run Earchive-executor in background to archive completed tasks.' },
  { match: 'Erefresh-executor',  hint: 'Analysis updated by Erefresh-executor. Proceed with user\'s request using fresh .qe/analysis/ data.' },
  { match: 'Ecompact-executor',  hint: 'Context saved by Ecompact-executor. Safe to continue. Use /Qresume in next session to restore.' },
  { match: 'Earchive-executor',  hint: 'Tasks archived by Earchive-executor. Completed files moved to .qe/.archive/.' },
  { match: 'Ecommit-executor',   hint: 'Commit created by Ecommit-executor. Report commit hash and summary to user.' },
  { match: 'Ecode-debugger',     hint: 'Ecode-debugger completed analysis. Review findings and apply suggested fixes.' },
  { match: 'Ecode-doc-writer',   hint: 'Documentation generated by Ecode-doc-writer. Review output with user.' },
  { match: 'Ecode-reviewer',     hint: 'Code review completed by Ecode-reviewer. Present findings and ask user about fixes.' },
  { match: 'Ecode-test-engineer', hint: 'Tests written by Ecode-test-engineer. Run tests to verify they pass.' },
  { match: 'Edeep-researcher',   hint: 'Research completed by Edeep-researcher. Summarize findings for user.' },
  { match: 'Edoc-generator',     hint: 'Document generated by Edoc-generator. Check output file and report path to user.' },
  { match: 'Egrad-writer',       hint: 'Chapter draft completed by Egrad-writer. Review academic style and citations.' },
  { match: 'Ehandoff-executor',  hint: 'Handoff document generated by Ehandoff-executor. Saved to .qe/handoffs/.' },
  { match: 'Epm-planner',        hint: 'Planning document created by Epm-planner. Review and confirm with user.' },
  { match: 'Eprofile-collector',  hint: 'Profile updated by Eprofile-collector. Data saved to .qe/profile/.' },
  { match: 'Eqa-orchestrator',   hint: '[CHAIN] Eqa-orchestrator completed quality loop. Report test/review/fix results to user.' },
  { match: 'codex-rescue',       hint: null, action: 'codex-poll' },
  { match: 'codex-review',       hint: '[CODEX] Codex review completed. Parse review findings and map to supervision verdict.' },
];

let agentChainMatched = false;
let codexPollStarted = false;

for (const { match, hint, action } of chains) {
  const regex = new RegExp(`\\b${match}\\b`);
  if (regex.test(messageStr)) {
    agentChainMatched = true;

    if (action === 'codex-poll') {
      // --- Spawn background poll watcher ---
      const signalFile = join(cwd, '.qe', 'agent-results', 'codex-ready.signal');

      // Clean up any stale signal from previous run
      try { if (existsSync(signalFile)) unlinkSync(signalFile); } catch {}

      const watcherScript = join(__dirname, 'lib', 'codex-poll-watcher.mjs');
      try {
        const child = spawn('node', [watcherScript, cwd, '--interval', '30', '--timeout', '3600'], {
          cwd,
          detached: true,
          stdio: 'ignore',
        });
        child.unref();
        codexPollStarted = true;
      } catch {
        // If spawn fails, fall back to manual hint
        codexPollStarted = false;
      }

      if (codexPollStarted) {
        hints.push('[CODEX] Codex rescue returned Done. A background watcher is now polling for file changes (30s interval, 1h timeout). Check `.qe/agent-results/codex-ready.signal` — when it appears, read it. If `detected: true`, Codex wrote files → proceed to verify with `git diff --stat`. If `detected: false` (timeout), use AskUserQuestion: (a) Keep waiting +1h (b) Retry Codex (c) Fallback to Claude. To check now: `cat .qe/agent-results/codex-ready.signal 2>/dev/null || echo "still polling"`');
      } else {
        hints.push('[CODEX] Codex rescue returned Done but watcher failed to start. Run `git diff --stat` manually to check for changes.');
      }
    } else if (hint) {
      hints.push(hint);
    }

    break;  // One chain action per notification
  }
}

// --- Persistent Mode Reinforcement ---
// Skip reinforcement if an agent chain was matched above.
try {
  if (!agentChainMatched) {
    const unifiedState = readUnifiedState(cwd);
    const pm = isPersistentModeActiveFromState(unifiedState);
    if (pm.active) {
      const completionPatterns = /\b(complet|finish|done|wrap|final|conclud|summar|handoff|hand off|result|output ready)\b/i;
      if (completionPatterns.test(messageStr)) {
        const reinforcement = getPersistentModeMessageFromState(unifiedState);
        if (reinforcement) {
          if (unifiedState.persistentMode) {
            unifiedState.persistentMode.reinforcements = (unifiedState.persistentMode.reinforcements || 0) + 1;
            try { writeUnifiedState(cwd, unifiedState); } catch {}
          }
          hints.push(reinforcement);
        }
      }
    }
  }
} catch {
  // Fault tolerance — never let persistent mode crash the notification hook
}

if (hints.length > 0) {
  console.log(JSON.stringify({
    continue: true,
    hookSpecificOutput: {
      hookEventName: "Notification",
      additionalContext: `[QE] ${hints.join(' | ')}`
    }
  }));
} else {
  console.log(JSON.stringify({ continue: true }));
}
